[package]
name = "text_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
# TODO: 0.12 -> 0.13
iced = { git = "https://github.com/iced-rs/iced.git", rev = "refs/tags/text-editor", features = [
    "debug",
] }
