[package]
name = "iceditor"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.12", features = ["debug", "highlighter", "tokio"] }
rfd = "0.15"
tokio = { version = "1.44", features = ["fs"] }
