[package]
name = "text_editor"
version = "0.1.0"
edition = "2024"

# TODO: update dependencies
[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", rev = "refs/tags/text-editor", features = [
    "debug",
] }
tokio = { version = "1.32", features = ["fs"] }
